### ISSUE TITLE
add topic fortran-stdlib

### ISSUE THREAD

**Issue by Beliavsky** [degawa/stdlib_modules#1]
I suggest adding the topic `fortran-stdlib` to the About section of https://github.com/degawa/stdlib_modules.

**Comment by degawa** [comment]
Hi, @Beliavsky 
Thank you for your suggestion and I'm sorry for bothering you.
I will add the About section and refer `fortran-stdlib` this weekend.

**Comment by degawa** [comment]
@Beliavsky 
I added some topics including `fortran-stdlib` to the About section.
Thanks again for your suggestion.
